
version: '3.8'

services:
  app:
    build: .
    ports:
      - "89:8080"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
      - ./vite.config.ts:/app/vite.config.ts
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.node.json:/app/tsconfig.node.json
      - ./tailwind.config.ts:/app/tailwind.config.ts
      - ./postcss.config.js:/app/postcss.config.js
      # Don't mount node_modules from host to container
    environment:
      - NODE_ENV=production
      - VITE_BASE_URL=/
      - DATABASE_URL=http://sqlite:3000
    restart: unless-stopped
    networks:
      - zentracker_network
    depends_on:
      - sqlite
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  sqlite:
    image: jonamat/sqlite-rest
    volumes:
      - sqlite_data:/data
    environment:
      - SQLITE_FILE=/data/zentracker.db
    # Removed the public port mapping so it's only accessible within the network
    networks:
      - zentracker_network
    restart: unless-stopped

networks:
  zentracker_network:

volumes:
  sqlite_data:
