
version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    restart: always

  frontend:
    build: .
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    restart: always

  backend:
    build: 
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./src/server:/app/src/server
      - ./data:/app/data
    environment:
      - NODE_ENV=development
      - PORT=3001
    restart: always

volumes:
  data:
