
version: '3.8'

services:
  app:
    build: .
    ports:
      - "89:8080"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
      - ./vite.config.ts:/app/vite.config.ts
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.node.json:/app/tsconfig.node.json
      - ./tailwind.config.ts:/app/tailwind.config.ts
      - ./postcss.config.js:/app/postcss.config.js
      - app_data:/app/data  # Store app data in a dedicated volume
    environment:
      - NODE_ENV=production
      - VITE_BASE_URL=/
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  zentracker_network:

volumes:
  app_data:  # Define the volume for persistent storage

