
version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "89:8080"  # Expose frontend directly
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    restart: always

  backend:
    build: 
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3001"  # Expose backend directly
    volumes:
      - ./src/server:/app/src/server
      - ./data:/app/data
    environment:
      - NODE_ENV=development
      - PORT=3001
    restart: always

volumes:
  data:
