
version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
      - ./vite.config.ts:/app/vite.config.ts
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.node.json:/app/tsconfig.node.json
      - ./tailwind.config.ts:/app/tailwind.config.ts
      - ./postcss.config.js:/app/postcss.config.js
      # Don't mount node_modules from host to container
      - sql_wasm_volume:/app/public/wasm
    environment:
      - NODE_ENV=production
      - VITE_BASE_URL=/
      # Add MIME type for WASM
      - VITE_SERVER_MIME_TYPES=wasm:application/wasm
    restart: unless-stopped
    networks:
      - zentracker_network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  zentracker_network:

volumes:
  sql_wasm_volume:
