
version: '3.8'

services:
  app:
    build: .
    ports:
      - "89:8080"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
      - ./vite.config.ts:/app/vite.config.ts
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.node.json:/app/tsconfig.node.json
      - ./tailwind.config.ts:/app/tailwind.config.ts
      - ./postcss.config.js:/app/postcss.config.js
      # Don't mount node_modules from host to container
    environment:
      - NODE_ENV=production
      - VITE_BASE_URL=/
      - VITE_DATABASE_URL=/api
    restart: unless-stopped
    networks:
      - zentracker_network
    depends_on:
      - sqlite
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  sqlite:
    build:
      context: .
      dockerfile: Dockerfile.sqlite
    volumes:
      - sqlite_data:/db
    networks:
      - zentracker_network
    restart: unless-stopped

  # Add a reverse proxy to handle API requests and CORS
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - sqlite
    networks:
      - zentracker_network
    restart: unless-stopped

networks:
  zentracker_network:

volumes:
  sqlite_data:
