
version: '3.8'

services:
  app:
    build: .
    ports:
      - "89:8080"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - VITE_BASE_URL=/
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
