
version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build: 
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3001"
    volumes:
      - ./src/server:/app/src/server
      - ./data:/app/data
    environment:
      - NODE_ENV=development
      - PORT=3001

volumes:
  data:
